server:
  port: 5000

spring:
  main:
    web-application-type: servlet

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/society_management}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Yashm123@}

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false


vaadin:
  productionMode: true
  launch-browser: false
  devmode:
    enabled: false
